namespace WalkHop;

/// <summary>Alle benutzersichtbaren Texte je Sprache (de/en). Single Source of Truth für die
/// Mehrsprachigkeit: Die XAML-Markup-Extension <see cref="TranslateExtension"/> und der
/// Code-Behind-Helfer <see cref="L"/> lesen ihre Strings hier. Deutsch ist die Fallback-Sprache;
/// fehlt ein Schlüssel in „en", wird der deutsche Text (oder zuletzt der Schlüssel selbst) gezeigt.</summary>
public static class Texte
{
    /// <summary>Übersetzung für Schlüssel + Sprache; Fallback: de → Schlüssel.</summary>
    public static string Hole(string key, string sprache)
    {
        var tabelle = sprache == "en" ? En : De;
        if (tabelle.TryGetValue(key, out var t)) return t;
        if (De.TryGetValue(key, out var d)) return d;   // Fallback Deutsch
        return key;                                       // letzter Fallback: Schlüssel sichtbar machen
    }

    // ---- Deutsch (Ausgangssprache, 1:1 die bisherigen Strings) ----------------
    public static readonly Dictionary<string, string> De = new()
    {
        // Shell / Navigation
        ["nav_start"] = "Start",
        ["nav_navigation"] = "Navigation",
        ["nav_konto"] = "Konto",
        ["nav_einstellungen"] = "Einstellungen",
        ["nav_beenden"] = "Beenden",
        ["nav_selbsttest"] = "Selbsttest",
        ["marke_untertitel"] = "Wandern und Sehenswürdigkeiten",   // Untertitel im Flyout-Kopf

        // Gemeinsame Begriffe / Dialog-Knöpfe
        ["abbrechen"] = "Abbrechen",
        ["ok"] = "OK",
        ["schliessen"] = "Schließen",
        ["ziel"] = "Ziel",
        ["mein_standort"] = "Mein Standort",

        // Gruppen-Position (Live-Standort teilen)
        ["gruppe_titel"] = "Gruppe",
        ["gruppe_code_msg"] = "Gib einen Gruppen-Code ein – alle mit demselben Code sehen sich gegenseitig live auf der Karte.",
        ["gruppe_code_placeholder"] = "Gruppen-Code",
        ["gruppe_beitreten_btn"] = "Beitreten",
        ["gruppe_name_titel"] = "Dein Name in der Gruppe",
        ["gruppe_name_msg"] = "Unter diesem Namen sehen dich die anderen.",
        ["gruppe_default_name"] = "Wanderer",
        ["gruppe_beigetreten"] = "Gruppe „{0}“ beigetreten",
        ["gruppe_aktiv_titel"] = "Gruppe: {0}",
        ["gruppe_verlassen"] = "Gruppe verlassen",
        ["gruppe_name_aendern"] = "Namen ändern",
        ["gruppe_verlassen_ok"] = "Gruppe verlassen",
        ["gruppe_erstellen"] = "Gruppe erstellen",
        ["gruppe_erstellen_btn"] = "Erstellen",
        ["gruppe_teilen"] = "📤 Gruppe teilen",
        ["gruppe_teilen_text"] = "Folge meiner Live-Position in WalkHop (oder im Browser): {0}",

        // Abmelden-Dialog (Shell „Beenden" + Konto)
        ["logout_titel"] = "Abmelden",
        ["logout_frage"] = "Du wirst abgemeldet (es wird wieder ein anonymes Testkonto genutzt).",
        ["abmelden_frage"] = "Du wirst abgemeldet und nutzt wieder ein anonymes Testkonto.",

        // ---- EinstellungenPage: Tabs ----
        ["einst_tab_allgemein"] = "Allgemein",
        ["einst_tab_navigation"] = "Navigation",
        ["einst_tab_karte"] = "Karte",
        ["einst_tab_anmeldung"] = "Anmeldung",

        // ---- Einstellungen: Allgemein ----
        ["einst_app_sprache"] = "App-Sprache",
        ["sprache_deutsch"] = "Deutsch",
        ["sprache_english"] = "English",
        ["einst_einheiten"] = "Einstellung der Einheiten",
        ["einheiten_metrisch"] = "Metrisch (km, m)",
        ["einheiten_imperial"] = "Imperial (mi, ft)",
        ["einst_bildschirm_titel"] = "Bildschirm entsperren",
        ["einst_bildschirm_sub"] = "Der Bildschirm wird bei Verwendung der Anwendung nicht gesperrt.",
        ["einst_kompakt_titel"] = "Kompakter Suchmodus",
        ["einst_kompakt_sub"] = "Ersetzt das Suchfeld durch das Suchsymbol.",
        ["einst_autotrack_titel"] = "Track automatisch aufzeichnen",
        ["einst_autotrack_sub"] = "Zeichnet die Strecke ab dem App-Start auf.",
        ["einst_fotosstart_titel"] = "Fotos beim Start anzeigen",
        ["einst_fotosstart_sub"] = "Foto-Ebene der Übersichtskarte direkt beim App-Start aktivieren (Standard: aus).",
        ["einst_fotoswlan_titel"] = "Fotos nur über WLAN hochladen",
        ["einst_fotoswlan_sub"] = "Aufnahmen werden erst bei WLAN hochgeladen – schont mobiles Datenvolumen.",

        // ---- Einstellungen: Navigation ----
        ["einst_sec_fortbewegung"] = "FORTBEWEGUNG",
        ["prof_fuss"] = "🥾 Fuß",
        ["prof_rad"] = "🚲 Rad",
        ["prof_auto"] = "🚗 Auto",
        ["einst_sec_wegtyp"] = "WEGTYP (FUSS)",
        ["wegtyp_fest"] = "Befestigt",
        ["wegtyp_neutral"] = "Neutral",
        ["wegtyp_natur"] = "Offroad",
        ["einst_sec_routenoptionen"] = "ROUTENOPTIONEN",
        ["einst_autobahn_titel"] = "Autobahn vermeiden",
        ["einst_gilt_auto"] = "Gilt für Auto-Routing.",
        ["einst_unbefestigt_titel"] = "Unbefestigte Wege vermeiden",
        ["einst_oberflaeche_titel"] = "Schlechte Oberflächen vermeiden",
        ["einst_gilt_rad"] = "Gilt für Rad-Routing.",
        ["einst_sec_farbmodus"] = "FARBMODUS",
        ["farb_auto"] = "Auto-Modus",
        ["farb_tag"] = "Tagmodus",
        ["farb_nacht"] = "Nachtmodus",
        ["einst_sec_tonsprache"] = "TON UND SPRACHE",
        ["einst_sprachnavi"] = "Sprachnavigation",
        ["einst_lautstaerke"] = "Lautstärke der Anweisungen",
        ["einst_benachr_titel"] = "Benachrichtigungstöne abspielen",
        ["einst_benachr_sub"] = "Höchstgeschwindigkeit, Neuberechnung der Route beim Verlassen.",
        ["einst_navisprache"] = "Sprache der Navigation",

        // ---- Einstellungen: Karte ----
        ["einst_sec_kartenmodus"] = "KARTENMODUS",
        ["km_wandern"] = "Wandern",
        ["km_standard"] = "Standard",
        ["km_satellit"] = "Satellit",
        ["km_dunkel"] = "Dunkel",
        ["einst_overlay_titel"] = "Wander-/Radwege-Overlay",
        ["einst_overlay_sub"] = "Markierte Wander- und Radrouten einblenden.",
        ["einst_drehung_titel"] = "Manuelle Kartendrehung",
        ["einst_drehung_sub"] = "Karte kann manuell gedreht werden.",
        ["einst_sec_standardpunkt"] = "STANDARD-PUNKT",
        ["einst_standardpunkt_info"] = "Bezugspunkt für die Entfernungsanzeige im Karten-Kontextmenü, wenn kein GPS-Standort verfügbar ist.",
        ["einst_standort_uebernehmen"] = "📍 Aktuellen Standort übernehmen",
        ["einst_zuruecksetzen_bbtor"] = "↺ Zurücksetzen (Brandenburger Tor)",
        ["einst_sec_offline"] = "OFFLINE-KARTEN",
        ["einst_offline_info"] = "Lädt die Kartenkacheln rund um deinen aktuellen Standort (~3 km) für die Offline-Nutzung.",
        ["einst_offline_laden_btn"] = "📥 Umgebung offline laden",
        ["einst_region_laden_btn"] = "🗺 Region offline speichern",
        ["einst_cache_leeren_btn"] = "🗑 Offline-Cache leeren",
        // Offline-Regionen + Pakete
        ["region_waehlen_titel"] = "Region wählen",
        ["region_keine"] = "Keine Regionen verfügbar.",
        ["region_schaetzung"] = "Ca. {0} Kacheln + {1} Fotos ≈ {2} MB. Jetzt offline speichern?",
        ["region_laden_btn"] = "Speichern",
        ["region_fertig"] = "Region „{0}“ gespeichert: {1} Kacheln, {2} Fotos ({3} MB).",
        ["region_fortschritt_kacheln"] = "Karten … {0}/{1}",
        ["region_fortschritt_fotos"] = "Fotos … {0}/{1}",
        ["offline_pakete_titel"] = "Meine Offline-Karten",
        ["offline_pakete_leer"] = "Noch keine Offline-Pakete gespeichert.",
        ["offline_paket_detail"] = "{0} Kacheln · {1} Fotos",
        ["offline_paket_fertig"] = "„{0}“ offline gespeichert: {1} Kacheln, {2} Fotos ({3} MB).",
        ["dlg_offline_btn"] = "💾 Tour offline speichern",

        // Cache-/Standardpunkt-Anzeige (Code)
        ["cache_strich"] = "Zwischenspeicher: –",
        ["cache_leer"] = "Zwischenspeicher: leer",
        ["cache_info"] = "Zwischenspeicher: {0} Kacheln · {1:0.0} MB",
        ["offline_fortschritt"] = "Offline laden … {0}/{1}",
        ["standardpunkt_label"] = "{0}: {1:0.0000}, {2:0.0000}",
        ["standardname_berlin"] = "Berlin Mitte",
        ["standardname_eigener"] = "eigener Punkt",
        ["quelle_gps"] = "GPS Pos.",
        ["entfernung_zeile"] = "📏 {0} (von {1})",

        // Offline-/Standardpunkt-/Cache-Dialoge (Einstellungen)
        ["offline_titel"] = "Offline-Karten",
        ["offline_premium_text"] = "Offline-Karten sind im Premium-Abo enthalten (5 €: 3 Karten, 8 €: alle) oder einzeln kaufbar (3 €).",
        ["offline_zum_konto"] = "Zum Konto",
        ["offline_laden_titel"] = "Offline laden",
        ["offline_kein_standort"] = "Aktueller Standort nicht verfügbar – bitte GPS aktivieren und erneut versuchen.",
        ["offline_gespeichert"] = "{0} Kacheln rund um deinen Standort offline gespeichert.",
        ["offline_fehler"] = "Beim Laden ist ein Fehler aufgetreten.",
        ["standardpunkt_titel"] = "Standard-Punkt",
        ["standardpunkt_kein_standort"] = "Aktueller Standort nicht verfügbar.",
        ["cache_leeren_titel"] = "Offline-Cache leeren",
        ["cache_leeren_frage"] = "Alle gespeicherten Kartenkacheln löschen?",
        ["cache_leeren_btn"] = "Leeren",

        // ---- Konto (Einstellungen-Tab 4 + KontoPage) ----
        ["konto_titel"] = "Konto",
        ["konto_testkonto"] = "Testkonto",
        ["konto_premium"] = "Premium",
        ["konto_premium_alle"] = "Premium (alle Funktionen)",
        ["konto_status_angemeldet"] = "Angemeldet als {0}",
        ["konto_status_anonym"] = "Anonymes Testkonto (ohne Anmeldung).",
        ["konto_kontingent_unbegrenzt"] = "Unbegrenzte Routen/Suchen.",
        ["konto_kontingent"] = "Heute {0}/{1} Gratis-Routen · {2} Route-Credits · {3} Offline-Karten.",
        ["konto_kontingent_genutzt"] = "Heute {0}/{1} Gratis-Routen genutzt · {2} Route-Credits · {3} Offline-Karten.",
        ["auth_titel_anlegen"] = "Konto anlegen oder anmelden",
        ["auth_titel_anmelden"] = "Anmelden",
        ["auth_titel_anmelden_oder_anlegen"] = "Anmelden oder Konto anlegen",
        ["auth_sub_konto"] = "Damit deine Aufnahmen und Käufe auf allen Geräten verfügbar sind.",
        ["feld_vorname"] = "Vorname",
        ["feld_name"] = "Name",
        ["feld_email"] = "E-Mail",
        ["feld_passwort"] = "Passwort",
        ["btn_anmelden"] = "Anmelden",
        ["btn_registrieren"] = "Registrieren",
        ["btn_premium_freischalten"] = "⭐ Premium freischalten",
        ["btn_premium_freischalten_plain"] = "Premium freischalten",
        ["btn_abmelden"] = "Abmelden",
        ["ueber_titel"] = "Über",
        ["version_label"] = "Version {0} (Build {1})",
        ["server_label"] = "Server: {0}",
        ["premium_titel"] = "Premium freischalten",
        ["premium_text"] = "Der In-App-Kauf folgt. Du kannst Premium vorerst auf spin1more.com (Stripe/PayPal) buchen – die Freischaltung gilt dann auch in der App.",
        ["premium_website"] = "Website öffnen",

        // KontoPage Tarife
        ["konto_tarife_titel"] = "Tarife",
        ["konto_tarif_gratis"] = "• Gratis: 2 Routen pro Tag",
        ["konto_tarif_einzel"] = "• Einzelne Route/Suche: 1 €  ·  Paket 10: 3 €",
        ["konto_tarif_offline"] = "• Offline-Karte: 3 €",
        ["konto_tarif_premium5"] = "• Premium 5 €/Monat: 3 Offline-Karten + unbegrenzt Suche/GPS",
        ["konto_tarif_premium8"] = "• Premium 8 €/Monat: alle Karten, alle Funktionen",
        ["konto_tarif_hinweis"] = "In-App-Kauf (App Store / Google Play) bzw. Stripe/PayPal auf spin1more.com.",

        // ---- MainPage (Navigation) ----
        ["mp_start"] = "Start",
        ["mp_stop"] = "Stop",
        ["mp_zurueck"] = "Zurück",
        ["mp_tour_titel"] = "TOUR",
        ["mp_zum_startpunkt"] = "🏁 Zum Startpunkt",
        ["mp_zum_naechsten"] = "📍 Zum nächsten Punkt",
        ["mp_route_umkehren"] = "🔄 Route umkehren",
        ["mp_hoehenprofil"] = "Höhenprofil",
        ["mp_hoehenprofil_werte"] = "Höhenprofil  ↑ {0:0} m  ↓ {1:0} m",
        ["mp_route_umgekehrt"] = "Route umgekehrt",
        ["mp_anfahrt_tour"] = "Anfahrt + Tour",
        ["route_zusammenfassung"] = "{0} · {1:0} min",

        // MainPage Status / Ansagen / Dialoge
        ["st_aufnahme_laeuft"] = "● Aufnahme läuft",
        ["st_tour_vorbereiten"] = "Tour wird vorbereitet …",
        ["st_gps_nicht_verfuegbar"] = "GPS nicht verfügbar",
        ["st_warte_gps"] = "Warte auf GPS-Standort …",
        ["st_noch_kein_gps"] = "Noch kein GPS-Standort",
        ["st_route_berechnet"] = "Route wird berechnet …",
        ["st_keine_route"] = "Keine Route gefunden",
        ["st_routing_nicht_erreichbar"] = "Routing gerade nicht erreichbar",
        ["st_route_ungueltig"] = "Route ungültig",
        ["ansage_ziel_erreicht"] = "Du hast dein Ziel erreicht.",
        ["st_ziel_erreicht"] = "🏁 Ziel erreicht",
        ["ansage_vorab"] = "In {0} Metern: {1}",
        ["st_route_neu"] = "↻ Route neu berechnet",
        ["paywall_titel"] = "Tageslimit erreicht",
        ["paywall_text"] = "Du hast deine {0} Gratis-Routen für heute genutzt. Mit Premium (oder Route-Credits) navigierst du weiter.",
        ["paywall_btn"] = "Premium / Konto",
        ["ktx_hierhin"] = "🥾 Hierhin navigieren",
        ["ktx_von_hier"] = "📍 Von hier starten",
        ["ktx_zum_plan"] = "➕ Zum Plan hinzufügen",
        ["st_start_gesetzt"] = "Start gesetzt – Ziel antippen",
        ["poi_wohin"] = "Wohin?",
        ["poi_nach_name"] = "🔍 Nach Name suchen …",
        ["poi_orte_suchen_titel"] = "Orte suchen",
        ["poi_orte_suchen_msg"] = "Name eines Ortes/POI:",
        ["poi_suchen_btn"] = "Suchen",
        ["poi_placeholder"] = "z. B. Museum",
        ["st_suche"] = "Suche …",
        ["st_nichts_gefunden"] = "Nichts im Kartenausschnitt gefunden",
        ["poi_treffer"] = "{0} Treffer",
        ["poi_dorthin_navigieren"] = "Dorthin navigieren?",
        ["poi_navigieren_btn"] = "Navigieren",
        ["st_suche_fehlgeschlagen"] = "Suche fehlgeschlagen",
        ["paywall_suche_text"] = "Du hast deine Gratis-Suchen für heute genutzt. Mit Premium (oder Such-Credits) suchst du unbegrenzt weiter.",
        ["offline_paywall_text"] = "Offline-Karten sind im Premium-Abo enthalten (5 €: 3 Karten, 8 €: alle) oder einzeln kaufbar (3 €). Im Konto freischalten.",
        ["st_offline_gespeichert"] = "✓ {0} Kacheln offline gespeichert",
        ["st_offline_fehler"] = "Offline-Fehler",
        ["ansage_sprachansagen_an"] = "Sprachansagen aktiviert.",
        ["st_route_umgekehrt"] = "🔄 Route läuft jetzt andersherum",
        ["st_plan_berechnet"] = "Plan wird berechnet …",
        ["st_kein_plan"] = "Kein Plan-Weg gefunden",
        ["st_plan_nicht_erreichbar"] = "Plan gerade nicht erreichbar",
        ["plan_los"] = "🧭 Plan ({0}) – Los",
        ["st_anfahrt_berechnet"] = "Anfahrt wird berechnet …",
        ["st_keine_anfahrt"] = "Keine Anfahrt gefunden",
        ["st_anfahrt_nicht_erreichbar"] = "Anfahrt gerade nicht erreichbar",
        ["aufnahme_name"] = "Aufnahme {0}",
        ["notif_navigation"] = "Navigation",

        // ---- UebersichtPage ----
        ["ue_such_placeholder"] = "Nach Name suchen …",
        ["ue_suche_kompakt"] = "Suchen",
        ["ue_standort_btn"] = "📍 Standort",
        ["ue_ort_placeholder"] = "Ort/Adresse als Mittelpunkt",
        ["ue_umkreis"] = "Umkreis-Suche",
        ["ue_bahnhof"] = "🚉 Bahnhof am Start",
        ["ue_radius"] = "Radius:",
        ["ue_dlg_navi"] = "🧭 Navigation starten",
        ["ue_dlg_gpx"] = "⬇ GPX-Route",
        ["ue_dlg_termine"] = "Details & Termine",
        ["ue_dlg_poi_titel"] = "✨ Sehenswürdigkeiten am Weg",

        // Facetten-Chips
        ["fac_alle"] = "Alle",
        ["fac_stadt"] = "🏙 Stadt",
        ["fac_see"] = "🌊 See & Wasser",
        ["fac_wandern_kurz"] = "🥾 bis 5 km",
        ["fac_wandern_mittel"] = "🥾 5–15 km",
        ["fac_wandern_lang"] = "🥾 ab 15 km",
        ["fac_wandern"] = "🥾 Wandern",
        ["fac_radtour"] = "🚴 Radtour",
        ["fac_rundtour"] = "🔄 Rundtour",
        ["fac_bahnanreise"] = "🚉 Bahn",
        ["fac_qualitytour"] = "⭐ QualityTour",
        ["fac_edgars"] = "🧭 Edgars",

        // Uebersicht Status / Dialoge
        ["ue_st_touren_laden"] = "Touren werden geladen …",
        ["ue_st_touren_fehler"] = "Touren konnten nicht geladen werden",
        ["ue_st_ort_suchen"] = "Ort wird gesucht …",
        ["ue_st_ort_nicht_gefunden"] = "Ort nicht gefunden",
        ["ue_st_ortssuche_fehlgeschlagen"] = "Ortssuche fehlgeschlagen",
        ["ue_ort_gefunden"] = "📍 {0} · {1} km",
        ["ue_st_kein_standort"] = "Kein Standort",
        ["ue_st_standort_nicht_verfuegbar"] = "Standort nicht verfügbar",
        ["ue_st_fotos_laden"] = "Fotos werden geladen …",
        ["ue_st_fotos_nicht_verfuegbar"] = "Fotos nicht verfügbar",
        ["ue_kein_kompass"] = "Kein Kompass im Gerät – die Karte dreht in Laufrichtung, sobald du gehst.",
        ["mittelpunkt_label"] = "Mittelpunkt: {0}",
        ["mittelpunkt_kartenmitte"] = "Kartenmitte",
        ["foto_navigieren"] = "🧭 Hierhin navigieren",
        ["ktx_navigation_zu"] = "🧭 Navigation zu",
        ["ktx_neue_wanderung"] = "🥾 Neue Wanderung ab hier",
        ["ktx_marker_setzen"] = "📌 Marker setzen",
        ["marker_titel"] = "Marker setzen",
        ["marker_msg"] = "Name des Markers:",
        ["marker_setzen_btn"] = "Setzen",
        ["marker_placeholder"] = "z. B. Treffpunkt",
        ["marker_default"] = "Marker",
        ["marker_gesetzt"] = "📌 Marker {0} gesetzt",
        ["nw_titel"] = "Neue Wanderung – wie lang?",
        ["nw_5km"] = "5 km zu Fuß",
        ["nw_10km"] = "10 km zu Fuß",
        ["nw_15km"] = "15 km zu Fuß",
        ["nw_20km_rad"] = "20 km Fahrrad",
        ["nw_erzeuge"] = "⏳ Erzeuge {0:0}-km-Touren …",
        ["nw_keine"] = "Keine Wanderung gefunden.",
        ["ue_gen_loeschen"] = "🗑 Berechnete Routen löschen",
        ["ue_gen_geloescht"] = "Berechnete Routen entfernt",
        ["ue_gen_kat"] = "Berechnete Rundtour",
        ["dlg_dauer_h"] = "{0}:{1:00} h",
        ["dlg_dauer_min"] = "{0} Min.",
        ["dlg_badges"] = "📏 {0:0.0} km   🕒 ≈ {1}",
        ["dlg_badges_grad"] = "   💪 {0}",
        ["poi_dist"] = "{0} m vom Weg",
        ["poi_dist_kat"] = "{0} · {1} m vom Weg",

        // ---- StartPage (derzeit nicht im Flyout verlinkt, aber kompiliert) ----
        ["sp_untertitel"] = "Berlin & Brandenburg entdecken – Touren und Navigation",
        ["sp_navigation"] = "🧭 Navigation",
        ["sp_uebersicht"] = "🗺 Übersichtskarte",
        ["sp_touren"] = "Touren",
        ["sp_tour_suche"] = "Tour suchen …",
        ["sp_leer_laden"] = "Touren werden geladen …",
        ["sp_leer_fehler"] = "Touren konnten nicht geladen werden.",
    };

    // ---- Englisch -------------------------------------------------------------
    public static readonly Dictionary<string, string> En = new()
    {
        // Shell / Navigation
        ["nav_start"] = "Start",
        ["nav_navigation"] = "Navigation",
        ["nav_konto"] = "Account",
        ["nav_einstellungen"] = "Settings",
        ["nav_beenden"] = "Log out",
        ["nav_selbsttest"] = "Self-test",
        ["marke_untertitel"] = "Hiking & sights",   // subtitle in the flyout header

        // Common terms / dialog buttons
        ["abbrechen"] = "Cancel",
        ["ok"] = "OK",
        ["schliessen"] = "Close",
        ["ziel"] = "Destination",
        ["mein_standort"] = "My location",

        // Group position (share live location)
        ["gruppe_titel"] = "Group",
        ["gruppe_code_msg"] = "Enter a group code – everyone with the same code sees each other live on the map.",
        ["gruppe_code_placeholder"] = "Group code",
        ["gruppe_beitreten_btn"] = "Join",
        ["gruppe_name_titel"] = "Your name in the group",
        ["gruppe_name_msg"] = "The others will see you under this name.",
        ["gruppe_default_name"] = "Hiker",
        ["gruppe_beigetreten"] = "Joined group “{0}”",
        ["gruppe_aktiv_titel"] = "Group: {0}",
        ["gruppe_verlassen"] = "Leave group",
        ["gruppe_name_aendern"] = "Change name",
        ["gruppe_verlassen_ok"] = "Left the group",
        ["gruppe_erstellen"] = "Create group",
        ["gruppe_erstellen_btn"] = "Create",
        ["gruppe_teilen"] = "📤 Share group",
        ["gruppe_teilen_text"] = "Follow my live location in WalkHop (or in the browser): {0}",

        // Log-out dialog
        ["logout_titel"] = "Log out",
        ["logout_frage"] = "You will be logged out (an anonymous test account will be used again).",
        ["abmelden_frage"] = "You will be logged out and use an anonymous test account again.",

        // Settings: tabs
        ["einst_tab_allgemein"] = "General",
        ["einst_tab_navigation"] = "Navigation",
        ["einst_tab_karte"] = "Map",
        ["einst_tab_anmeldung"] = "Account",

        // Settings: General
        ["einst_app_sprache"] = "App language",
        ["sprache_deutsch"] = "Deutsch",
        ["sprache_english"] = "English",
        ["einst_einheiten"] = "Units",
        ["einheiten_metrisch"] = "Metric (km, m)",
        ["einheiten_imperial"] = "Imperial (mi, ft)",
        ["einst_bildschirm_titel"] = "Keep screen on",
        ["einst_bildschirm_sub"] = "The screen will not lock while you use the app.",
        ["einst_kompakt_titel"] = "Compact search mode",
        ["einst_kompakt_sub"] = "Replaces the search field with the search icon.",
        ["einst_autotrack_titel"] = "Record track automatically",
        ["einst_autotrack_sub"] = "Records your route from app start.",
        ["einst_fotosstart_titel"] = "Show photos at start",
        ["einst_fotosstart_sub"] = "Enable the overview map's photo layer at app start (default: off).",
        ["einst_fotoswlan_titel"] = "Upload photos over Wi-Fi only",
        ["einst_fotoswlan_sub"] = "Recordings are uploaded only on Wi-Fi – saves mobile data.",

        // Settings: Navigation
        ["einst_sec_fortbewegung"] = "TRAVEL MODE",
        ["prof_fuss"] = "🥾 Walk",
        ["prof_rad"] = "🚲 Bike",
        ["prof_auto"] = "🚗 Car",
        ["einst_sec_wegtyp"] = "PATH TYPE (WALK)",
        ["wegtyp_fest"] = "Paved",
        ["wegtyp_neutral"] = "Neutral",
        ["wegtyp_natur"] = "Offroad",
        ["einst_sec_routenoptionen"] = "ROUTE OPTIONS",
        ["einst_autobahn_titel"] = "Avoid highways",
        ["einst_gilt_auto"] = "Applies to car routing.",
        ["einst_unbefestigt_titel"] = "Avoid unpaved roads",
        ["einst_oberflaeche_titel"] = "Avoid poor surfaces",
        ["einst_gilt_rad"] = "Applies to bike routing.",
        ["einst_sec_farbmodus"] = "COLOR MODE",
        ["farb_auto"] = "Auto",
        ["farb_tag"] = "Day",
        ["farb_nacht"] = "Night",
        ["einst_sec_tonsprache"] = "SOUND & VOICE",
        ["einst_sprachnavi"] = "Voice navigation",
        ["einst_lautstaerke"] = "Instruction volume",
        ["einst_benachr_titel"] = "Play notification sounds",
        ["einst_benachr_sub"] = "Speed limit, route recalculation when leaving the route.",
        ["einst_navisprache"] = "Navigation language",

        // Settings: Map
        ["einst_sec_kartenmodus"] = "MAP STYLE",
        ["km_wandern"] = "Hiking",
        ["km_standard"] = "Standard",
        ["km_satellit"] = "Satellite",
        ["km_dunkel"] = "Dark",
        ["einst_overlay_titel"] = "Hiking/cycling trails overlay",
        ["einst_overlay_sub"] = "Show marked hiking and cycling routes.",
        ["einst_drehung_titel"] = "Manual map rotation",
        ["einst_drehung_sub"] = "The map can be rotated manually.",
        ["einst_sec_standardpunkt"] = "DEFAULT POINT",
        ["einst_standardpunkt_info"] = "Reference point for the distance shown in the map context menu when no GPS location is available.",
        ["einst_standort_uebernehmen"] = "📍 Use current location",
        ["einst_zuruecksetzen_bbtor"] = "↺ Reset (Brandenburg Gate)",
        ["einst_sec_offline"] = "OFFLINE MAPS",
        ["einst_offline_info"] = "Downloads the map tiles around your current location (~3 km) for offline use.",
        ["einst_offline_laden_btn"] = "📥 Download area for offline use",
        ["einst_region_laden_btn"] = "🗺 Save region offline",
        ["einst_cache_leeren_btn"] = "🗑 Clear offline cache",
        // Offline regions + packages
        ["region_waehlen_titel"] = "Choose region",
        ["region_keine"] = "No regions available.",
        ["region_schaetzung"] = "Approx. {0} tiles + {1} photos ≈ {2} MB. Save offline now?",
        ["region_laden_btn"] = "Save",
        ["region_fertig"] = "Region “{0}” saved: {1} tiles, {2} photos ({3} MB).",
        ["region_fortschritt_kacheln"] = "Maps … {0}/{1}",
        ["region_fortschritt_fotos"] = "Photos … {0}/{1}",
        ["offline_pakete_titel"] = "My offline maps",
        ["offline_pakete_leer"] = "No offline packages saved yet.",
        ["offline_paket_detail"] = "{0} tiles · {1} photos",
        ["offline_paket_fertig"] = "“{0}” saved offline: {1} tiles, {2} photos ({3} MB).",
        ["dlg_offline_btn"] = "💾 Save tour offline",

        // Cache / default point (code)
        ["cache_strich"] = "Cache: –",
        ["cache_leer"] = "Cache: empty",
        ["cache_info"] = "Cache: {0} tiles · {1:0.0} MB",
        ["offline_fortschritt"] = "Downloading offline … {0}/{1}",
        ["standardpunkt_label"] = "{0}: {1:0.0000}, {2:0.0000}",
        ["standardname_berlin"] = "Berlin center",
        ["standardname_eigener"] = "own point",
        ["quelle_gps"] = "GPS pos.",
        ["entfernung_zeile"] = "📏 {0} (from {1})",

        // Offline / default-point / cache dialogs
        ["offline_titel"] = "Offline maps",
        ["offline_premium_text"] = "Offline maps are included with Premium (€5: 3 maps, €8: all) or available individually (€3).",
        ["offline_zum_konto"] = "Go to account",
        ["offline_laden_titel"] = "Offline download",
        ["offline_kein_standort"] = "Current location unavailable – please enable GPS and try again.",
        ["offline_gespeichert"] = "{0} tiles around your location saved for offline use.",
        ["offline_fehler"] = "An error occurred during download.",
        ["standardpunkt_titel"] = "Default point",
        ["standardpunkt_kein_standort"] = "Current location unavailable.",
        ["cache_leeren_titel"] = "Clear offline cache",
        ["cache_leeren_frage"] = "Delete all saved map tiles?",
        ["cache_leeren_btn"] = "Clear",

        // Account
        ["konto_titel"] = "Account",
        ["konto_testkonto"] = "Test account",
        ["konto_premium"] = "Premium",
        ["konto_premium_alle"] = "Premium (all features)",
        ["konto_status_angemeldet"] = "Signed in as {0}",
        ["konto_status_anonym"] = "Anonymous test account (no sign-in).",
        ["konto_kontingent_unbegrenzt"] = "Unlimited routes/searches.",
        ["konto_kontingent"] = "Today {0}/{1} free routes · {2} route credits · {3} offline maps.",
        ["konto_kontingent_genutzt"] = "Used {0}/{1} free routes today · {2} route credits · {3} offline maps.",
        ["auth_titel_anlegen"] = "Create account or sign in",
        ["auth_titel_anmelden"] = "Sign in",
        ["auth_titel_anmelden_oder_anlegen"] = "Sign in or create account",
        ["auth_sub_konto"] = "So your recordings and purchases are available on all devices.",
        ["feld_vorname"] = "First name",
        ["feld_name"] = "Last name",
        ["feld_email"] = "Email",
        ["feld_passwort"] = "Password",
        ["btn_anmelden"] = "Sign in",
        ["btn_registrieren"] = "Register",
        ["btn_premium_freischalten"] = "⭐ Unlock Premium",
        ["btn_premium_freischalten_plain"] = "Unlock Premium",
        ["btn_abmelden"] = "Log out",
        ["ueber_titel"] = "About",
        ["version_label"] = "Version {0} (build {1})",
        ["server_label"] = "Server: {0}",
        ["premium_titel"] = "Unlock Premium",
        ["premium_text"] = "In-app purchase is coming. For now you can subscribe to Premium on spin1more.com (Stripe/PayPal) – it will also unlock in the app.",
        ["premium_website"] = "Open website",

        // Account plans
        ["konto_tarife_titel"] = "Plans",
        ["konto_tarif_gratis"] = "• Free: 2 routes per day",
        ["konto_tarif_einzel"] = "• Single route/search: €1  ·  Pack of 10: €3",
        ["konto_tarif_offline"] = "• Offline map: €3",
        ["konto_tarif_premium5"] = "• Premium €5/month: 3 offline maps + unlimited search/GPS",
        ["konto_tarif_premium8"] = "• Premium €8/month: all maps, all features",
        ["konto_tarif_hinweis"] = "In-app purchase (App Store / Google Play) or Stripe/PayPal on spin1more.com.",

        // MainPage (Navigation)
        ["mp_start"] = "Start",
        ["mp_stop"] = "Stop",
        ["mp_zurueck"] = "Back",
        ["mp_tour_titel"] = "TOUR",
        ["mp_zum_startpunkt"] = "🏁 To start point",
        ["mp_zum_naechsten"] = "📍 To next point",
        ["mp_route_umkehren"] = "🔄 Reverse route",
        ["mp_hoehenprofil"] = "Elevation profile",
        ["mp_hoehenprofil_werte"] = "Elevation profile  ↑ {0:0} m  ↓ {1:0} m",
        ["mp_route_umgekehrt"] = "Route reversed",
        ["mp_anfahrt_tour"] = "Approach + tour",
        ["route_zusammenfassung"] = "{0} · {1:0} min",

        // MainPage status / announcements / dialogs
        ["st_aufnahme_laeuft"] = "● Recording",
        ["st_tour_vorbereiten"] = "Preparing tour …",
        ["st_gps_nicht_verfuegbar"] = "GPS unavailable",
        ["st_warte_gps"] = "Waiting for GPS location …",
        ["st_noch_kein_gps"] = "No GPS location yet",
        ["st_route_berechnet"] = "Calculating route …",
        ["st_keine_route"] = "No route found",
        ["st_routing_nicht_erreichbar"] = "Routing currently unavailable",
        ["st_route_ungueltig"] = "Invalid route",
        ["ansage_ziel_erreicht"] = "You have reached your destination.",
        ["st_ziel_erreicht"] = "🏁 Destination reached",
        ["ansage_vorab"] = "In {0} meters: {1}",
        ["st_route_neu"] = "↻ Route recalculated",
        ["paywall_titel"] = "Daily limit reached",
        ["paywall_text"] = "You've used your {0} free routes for today. With Premium (or route credits) you can keep navigating.",
        ["paywall_btn"] = "Premium / Account",
        ["ktx_hierhin"] = "🥾 Navigate here",
        ["ktx_von_hier"] = "📍 Start from here",
        ["ktx_zum_plan"] = "➕ Add to plan",
        ["st_start_gesetzt"] = "Start set – tap a destination",
        ["poi_wohin"] = "Where to?",
        ["poi_nach_name"] = "🔍 Search by name …",
        ["poi_orte_suchen_titel"] = "Search places",
        ["poi_orte_suchen_msg"] = "Name of a place/POI:",
        ["poi_suchen_btn"] = "Search",
        ["poi_placeholder"] = "e.g. museum",
        ["st_suche"] = "Searching …",
        ["st_nichts_gefunden"] = "Nothing found in the map view",
        ["poi_treffer"] = "{0} results",
        ["poi_dorthin_navigieren"] = "Navigate there?",
        ["poi_navigieren_btn"] = "Navigate",
        ["st_suche_fehlgeschlagen"] = "Search failed",
        ["paywall_suche_text"] = "You've used your free searches for today. With Premium (or search credits) you can keep searching.",
        ["offline_paywall_text"] = "Offline maps are included with Premium (€5: 3 maps, €8: all) or available individually (€3). Unlock in your account.",
        ["st_offline_gespeichert"] = "✓ {0} tiles saved offline",
        ["st_offline_fehler"] = "Offline error",
        ["ansage_sprachansagen_an"] = "Voice announcements enabled.",
        ["st_route_umgekehrt"] = "🔄 Route now runs in reverse",
        ["st_plan_berechnet"] = "Calculating plan …",
        ["st_kein_plan"] = "No plan route found",
        ["st_plan_nicht_erreichbar"] = "Plan currently unavailable",
        ["plan_los"] = "🧭 Plan ({0}) – Go",
        ["st_anfahrt_berechnet"] = "Calculating approach …",
        ["st_keine_anfahrt"] = "No approach found",
        ["st_anfahrt_nicht_erreichbar"] = "Approach currently unavailable",
        ["aufnahme_name"] = "Recording {0}",
        ["notif_navigation"] = "Navigation",

        // UebersichtPage
        ["ue_such_placeholder"] = "Search by name …",
        ["ue_suche_kompakt"] = "Search",
        ["ue_standort_btn"] = "📍 Location",
        ["ue_ort_placeholder"] = "Place/address as center",
        ["ue_umkreis"] = "Radius search",
        ["ue_bahnhof"] = "🚉 Station at start",
        ["ue_radius"] = "Radius:",
        ["ue_dlg_navi"] = "🧭 Start navigation",
        ["ue_dlg_gpx"] = "⬇ GPX route",
        ["ue_dlg_termine"] = "Details & dates",
        ["ue_dlg_poi_titel"] = "✨ Sights along the way",

        // Facet chips
        ["fac_alle"] = "All",
        ["fac_stadt"] = "🏙 City",
        ["fac_see"] = "🌊 Lake & water",
        ["fac_wandern_kurz"] = "🥾 up to 5 km",
        ["fac_wandern_mittel"] = "🥾 5–15 km",
        ["fac_wandern_lang"] = "🥾 from 15 km",
        ["fac_wandern"] = "🥾 Hiking",
        ["fac_radtour"] = "🚴 Cycling",
        ["fac_rundtour"] = "🔄 Loop",
        ["fac_bahnanreise"] = "🚉 Train",
        ["fac_qualitytour"] = "⭐ Quality tour",
        ["fac_edgars"] = "🧭 Edgar's",

        // Uebersicht status / dialogs
        ["ue_st_touren_laden"] = "Loading tours …",
        ["ue_st_touren_fehler"] = "Tours could not be loaded",
        ["ue_st_ort_suchen"] = "Searching place …",
        ["ue_st_ort_nicht_gefunden"] = "Place not found",
        ["ue_st_ortssuche_fehlgeschlagen"] = "Place search failed",
        ["ue_ort_gefunden"] = "📍 {0} · {1} km",
        ["ue_st_kein_standort"] = "No location",
        ["ue_st_standort_nicht_verfuegbar"] = "Location unavailable",
        ["ue_st_fotos_laden"] = "Loading photos …",
        ["ue_st_fotos_nicht_verfuegbar"] = "Photos unavailable",
        ["ue_kein_kompass"] = "No compass in this device – the map rotates to your heading once you start moving.",
        ["mittelpunkt_label"] = "Center: {0}",
        ["mittelpunkt_kartenmitte"] = "Map center",
        ["foto_navigieren"] = "🧭 Navigate here",
        ["ktx_navigation_zu"] = "🧭 Navigate to",
        ["ktx_neue_wanderung"] = "🥾 New hike from here",
        ["ktx_marker_setzen"] = "📌 Place marker",
        ["marker_titel"] = "Place marker",
        ["marker_msg"] = "Marker name:",
        ["marker_setzen_btn"] = "Place",
        ["marker_placeholder"] = "e.g. meeting point",
        ["marker_default"] = "Marker",
        ["marker_gesetzt"] = "📌 Marker {0} placed",
        ["nw_titel"] = "New hike – how long?",
        ["nw_5km"] = "5 km on foot",
        ["nw_10km"] = "10 km on foot",
        ["nw_15km"] = "15 km on foot",
        ["nw_20km_rad"] = "20 km by bike",
        ["nw_erzeuge"] = "⏳ Generating {0:0}-km tours …",
        ["nw_keine"] = "No hike found.",
        ["ue_gen_loeschen"] = "🗑 Delete calculated routes",
        ["ue_gen_geloescht"] = "Calculated routes removed",
        ["ue_gen_kat"] = "Calculated round trip",
        ["dlg_dauer_h"] = "{0}:{1:00} h",
        ["dlg_dauer_min"] = "{0} min",
        ["dlg_badges"] = "📏 {0:0.0} km   🕒 ≈ {1}",
        ["dlg_badges_grad"] = "   💪 {0}",
        ["poi_dist"] = "{0} m from the path",
        ["poi_dist_kat"] = "{0} · {1} m from the path",

        // StartPage
        ["sp_untertitel"] = "Discover Berlin & Brandenburg – tours and navigation",
        ["sp_navigation"] = "🧭 Navigation",
        ["sp_uebersicht"] = "🗺 Overview map",
        ["sp_touren"] = "Tours",
        ["sp_tour_suche"] = "Search tours …",
        ["sp_leer_laden"] = "Loading tours …",
        ["sp_leer_fehler"] = "Tours could not be loaded.",
    };
}
